#!/bin/sh

sxhkd &
r809-wm-start

bspc monitor -d 雜項 通訊 密碼 


bspc config border_width         0
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config presel_feedback_color "#777777"
bspc config focus_follows_pointer true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

