#!/bin/sh


source ~/.r809env 
sxhkd &
compton --backend glx --paint-on-overlay --glx-no-stencil --vsync opengl-swc --unredir-if-possible &
dnust &
fcitx-autostart &
xrandr --output $monitor1 --auto --output $monitor2 $monitorOpt $monitor1 &
polybar r809 &
feh --randomize --bg-fill ~/Pictures/Wallpapers/* &
bash ~/r809Script/TouchpadInit.sh  &
randr --dpi 120 &

bspc monitor -d I II III IV V VI VII VIII IX X


bspc config border_width         0
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config presel_feedback_color "#777777"
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

